[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orca-manipulation"
version = "0.1.0"
description = "SouthGrid manipulation examples for OrcaGym"
requires-python = ">=3.12,<3.13"
dependencies = ["orca-gym==26.7.3"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff.lint]
"per-file-ignores" = { "**/*.py" = ["E402"] }
