l_arm = {
    "joint_names": [
        "shoulder_pitch_l_joint",
        "shoulder_roll_l_joint",
        "shoulder_yaw_l_joint",
        "elbow_pitch_l_joint",
        "elbow_yaw_l_joint",
        "wrist_pitch_l_joint",
        "wrist_roll_l_joint",
    ],
    "neutral_joint_values": [-0.8, 0.71, -0.86, -1.62, 0.98, 0, 0],
    "motors_names": [
        "motor_shoulder_pitch_l",
        "motor_shoulder_roll_l",
        "motor_shoulder_yaw_l",
        "motor_elbow_pitch_l",
        "motor_elbow_yaw_l",
        "motor_wrist_pitch_l",
        "motor_wrist_roll_l",
    ],
    "motors_init_ctrl": [0, 0, 0, 0, 0, 0, 0],
    "motors_ranges": [
        (-91, 91),
        (-95, 95),
        (-35, 35),
        (-35, 35),
        (-24, 24),
        (-6.3, 6.3),
        (-6.3, 6.3),
    ],
    "positions_names": [
        "pos_shoulder_pitch_l",
        "pos_shoulder_roll_l",
        "pos_shoulder_yaw_l",
        "pos_elbow_pitch_l",
        "pos_elbow_yaw_l",
        "pos_wrist_pitch_l",
        "pos_wrist_roll_l",
    ],
    "positions_init_ctrl": [-0.8, 0.71, -0.86, -1.62, 0.98, 0, 0],
    "positions_ranges": [
        (-2.96706, 2.96706),
        (-1.8326, 1.0472),
        (-2.96706, 2.96706),
        (-2.61799, 0.261799),
        (-2.96706, 2.96706),
        (-1.309, 1.65806),
        (-1.0472, 0.785398),
    ],
    "ee_site_name": "ee_center_site_l",
}

r_arm = {
    "joint_names": [
        "shoulder_pitch_r_joint",
        "shoulder_roll_r_joint",
        "shoulder_yaw_r_joint",
        "elbow_pitch_r_joint",
        "elbow_yaw_r_joint",
        "wrist_pitch_r_joint",
        "wrist_roll_r_joint",
    ],
    "neutral_joint_values": [-0.8, -0.71, 0.86, -1.62, -0.98, 0, 0],
    "motors_names": [
        "motor_shoulder_pitch_r",
        "motor_shoulder_roll_r",
        "motor_shoulder_yaw_r",
        "motor_elbow_pitch_r",
        "motor_elbow_yaw_r",
        "motor_wrist_pitch_r",
        "motor_wrist_roll_r",
    ],
    "motors_init_ctrl": [0, 0, 0, 0, 0, 0, 0],
    "motors_ranges": [
        (-91, 91),
        (-95, 95),
        (-35, 35),
        (-35, 35),
        (-24, 24),
        (-6.3, 6.3),
        (-6.3, 6.3),
    ],
    "positions_names": [
        "pos_shoulder_pitch_r",
        "pos_shoulder_roll_r",
        "pos_shoulder_yaw_r",
        "pos_elbow_pitch_r",
        "pos_elbow_yaw_r",
        "pos_wrist_pitch_r",
        "pos_wrist_roll_r",
    ],
    "positions_init_ctrl": [-0.8, -0.71, 0.86, -1.62, -0.98, 0, 0],
    "positions_ranges": [
        (-2.96706, 2.96706),
        (-1.8326, 1.0472),
        (-2.96706, 2.96706),
        (-2.61799, 0.261799),
        (-2.96706, 2.96706),
        (-1.309, 1.65806),
        (-0.785398, 1.0472),
    ],
    "ee_site_name": "ee_center_site_r",
}

gripper_l = {
    "joint_names": [
        "left_thumb_1_joint",
        "left_thumb_2_joint",
        "left_thumb_3_joint",
        "left_thumb_4_joint",
        "left_index_1_joint",
        "left_index_2_joint",
        "left_middle_1_joint",
        "left_middle_2_joint",
        "left_ring_1_joint",
        "left_ring_2_joint",
        "left_little_1_joint",
        "left_little_2_joint",
    ],
    "actuator_names": [
        "pos_left_thumb_1",
        "pos_left_thumb_2",
        "pos_left_thumb_3",
        "pos_left_thumb_4",
        "pos_left_index_1",
        "pos_left_index_2",
        "pos_left_middle_1",
        "pos_left_middle_2",
        "pos_left_ring_1",
        "pos_left_ring_2",
        "pos_left_little_1",
        "pos_left_little_2",
    ],
    "actuator_ranges": [(0, 1.24616), (0, 0.48), (0, 0.3578), (0, 0.2775), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5),(0, 0.5),],
    
    "init_ctrl": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
}

gripper_r = {
    "joint_names": [
        "right_thumb_1_joint",
        "right_thumb_2_joint",
        "right_thumb_3_joint",
        "right_thumb_4_joint",
        "right_index_1_joint",
        "right_index_2_joint",
        "right_middle_1_joint",
        "right_middle_2_joint",
        "right_ring_1_joint",
        "right_ring_2_joint",
        "right_little_1_joint",
        "right_little_2_joint",
    ],
    "actuator_names": [
        "pos_right_thumb_1",
        "pos_right_thumb_2",
        "pos_right_thumb_3",
        "pos_right_thumb_4",
        "pos_right_index_1",
        "pos_right_index_2",
        "pos_right_middle_1",
        "pos_right_middle_2",
        "pos_right_ring_1",
        "pos_right_ring_2",
        "pos_right_little_1",
        "pos_right_little_2",
    ],
    "actuator_ranges": [(0, 1.24616), (0, 0.48), (0, 0.3578), (0, 0.2775), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5), (0, 0.5),(0, 0.5),],
    "init_ctrl": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
}
motors_group = 0
positions_group = 1

base_body = "pelvis"
